#!/bin/sh

userresources=$HOME/.config/Xresources
usermodmap=$HOME/.Xmodmap
userprofile=$HOME/.config/profile

# merge in defaults and keymaps

[ -f "$userresources" ] && xrdb -merge "$userresources"

[ -f "$usermodmap" ] && xmodmap "$usermodmap"

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Tow GPU setting
# xrandr --setprovideroutputsource modesetting NVIDIA-0
# xrandr --auto

[ -f "$userprofile" ] && source "$userprofile"

exec $1
